name: Build Astrea

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:7-slim
    steps:
      - name: Install build essentials
        run: |
          microdnf install git xz tar findutils clang curl
          curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
          sh init.sh -y

      - name: Clone source
        run: git clone https://github.com/Yu-Vitaqua-fer-Chronos/Astrea --depth 1

      - name: Build with Nimble
        run: cd Astrea && ~/.nimble/bin/nimble -y --nim:~/.nimble/bin/nim build -d:release -d:speed

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./Astrea/astrea
