name: Build Astrea

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:8-slim
    steps:
      - name: Install build essentials
        run: |
          microdnf install git xz tar findutils clang curl

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone source
        uses: actions/checkout@v3

      - name: Build with Nimble
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          nimble -y build -d:release -d:speed

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: $GITHUB_WORKSPACE/astrea_client
