name: Build Astrea

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:9-slim
    steps:
      - name: Install build essentials
        run: |
          microdnf install git xz tar findutils clang curl
          curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
          sh init.sh -y

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build with Nimble
        run: ~/.nimble/bin/nimble --nim:~/.nimble/bin/nim build -d:release -d:speed

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./astrea
